/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SocialLinks = IDL.Record({
  'x' : IDL.Text,
  'linkedin' : IDL.Text,
  'telegram' : IDL.Text,
  'github' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'socialLinks' : SocialLinks,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'parentId' : IDL.Opt(IDL.Nat),
  'proposalId' : IDL.Nat64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Nat64, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addFavorite' : IDL.Func([IDL.Nat64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat64], [IDL.Vec(Comment)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat64)], ['query']),
  'getPrincipalByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'removeFavorite' : IDL.Func([IDL.Nat64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'upvoteComment' : IDL.Func([IDL.Nat, IDL.Nat64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SocialLinks = IDL.Record({
    'x' : IDL.Text,
    'linkedin' : IDL.Text,
    'telegram' : IDL.Text,
    'github' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'socialLinks' : SocialLinks,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'parentId' : IDL.Opt(IDL.Nat),
    'proposalId' : IDL.Nat64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Nat64, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addFavorite' : IDL.Func([IDL.Nat64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat64], [IDL.Vec(Comment)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat64)], ['query']),
    'getPrincipalByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'removeFavorite' : IDL.Func([IDL.Nat64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'upvoteComment' : IDL.Func([IDL.Nat, IDL.Nat64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };