/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'upvotes' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'parentId' : [] | [bigint],
  'proposalId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface SocialLinks {
  'x' : string,
  'linkedin' : string,
  'telegram' : string,
  'github' : string,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'socialLinks' : SocialLinks,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface ProposalVoteCounts {
  'upvotes' : bigint,
  'downvotes' : bigint,
}
export interface ForumTopic {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'author' : Principal,
  'category' : string,
  'proposalId' : [] | [bigint],
  'createdAt' : bigint,
  'replyCount' : bigint,
  'upvotes' : bigint,
}
export interface ForumReply {
  'id' : bigint,
  'topicId' : bigint,
  'body' : string,
  'author' : Principal,
  'parentId' : [] | [bigint],
  'createdAt' : bigint,
  'upvotes' : bigint,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, [] | [bigint], string], bigint>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerVoteOnProposal' : ActorMethod<[bigint], [] | [boolean]>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getFavorites' : ActorMethod<[], BigUint64Array>,
  'getForumReplies' : ActorMethod<[bigint], Array<ForumReply>>,
  'getForumTopicById' : ActorMethod<[bigint], [] | [ForumTopic]>,
  'getForumTopics' : ActorMethod<[[] | [string], bigint, bigint], Array<ForumTopic>>,
  'getForumTopicsCount' : ActorMethod<[[] | [string]], bigint>,
  'getPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getProposalVoteCounts' : ActorMethod<[bigint], ProposalVoteCounts>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'createForumReply' : ActorMethod<[bigint, string, [] | [bigint]], bigint>,
  'createForumTopic' : ActorMethod<[string, string, string, [] | [bigint]], bigint>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'removeVoteFromProposal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'upvoteComment' : ActorMethod<[bigint, bigint], undefined>,
  'upvoteForumReply' : ActorMethod<[bigint, bigint], undefined>,
  'upvoteForumTopic' : ActorMethod<[bigint], undefined>,
  'voteOnProposal' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
